# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/my-blog.ipynb.

# %% auto #0
__all__ = ['app', 'rt', 'navbar', 'footer', 'get', 'landing', 'writing', 'research_entry', 'research', 'get_note_paths',
           'previews', 'load_note', 'preview_entry', 'full_note']

# %% ../nbs/my-blog.ipynb #ddf5c318
from pathlib import Path

from fasthtml.common import *
import frontmatter
from monsterui.all import *
import nbdev

# %% ../nbs/my-blog.ipynb #035847fc
def navbar():
    return NavBar(
        A("about", href='/'),
        A("notes", href="/notes"),
        A("writing", href='/writing'),
        brand=A(H3("Grayson Badgley"), href='/')
        )


def footer():
    return Container(DividerLine(), P("powered by fasthtml", cls=TextT.lead+TextT.sm), cls='mt-auto pb-4')

app, rt = fast_app(hdrs=(Theme.blue.headers()), title="Grayson Badgley")

@rt('/')
def get(): return Title("g badgley"), Div(navbar(), landing(), footer(), cls='min-h-screen flex flex-col')

# %% ../nbs/my-blog.ipynb #480caff3
def landing():
     
    return Container(   
        
        P("Hi, I'm Grayson, and I'm passionate about helping society address climate change."),
        
        P(
            "Right now, I lead research at ", A('CarbonPlan', href='https://carbonplan.org', cls='underline text-black'), " to ensure the scientific integrity of the global carbon market. " \
            "My work has exposed hundreds of millions of dollars in bad offset credits. "
        )
        ,
        
        P(
            "Previously, I spent roughly a decade in academia studying forest ecology and plant physiology. " \
            "I spent most of that time staring at leaves and processing terabytes of satellite imagery in an effort to improve how we measure photosynthesis at the global scale. "
        )
        ,

        P(
            "Before that, I was the first data scientist at Lyft and worked on some of our first dispatching algorithms. "
        )
        ,
    cls=(ContainerT.xs, 'space-y-4 text-left pt-16 w-full')
    )

# %% ../nbs/my-blog.ipynb #0882e384
def writing():
    return Container(
        H2("Writing"),
        H2("Research"), research(),
    cls=(ContainerT.xs, 'space-y-4 pt-16')
    )

# %% ../nbs/my-blog.ipynb #adbb9a70
def research_entry(title, author_str, yr, outlet, doi):
    return A(
        Div(
            P(Strong(title)),
            P(f"{author_str} ({yr}), ", Strong(outlet), cls='!text-black'),
            cls='text-left'
        )
        , href=doi, cls='block space-y-2 text-black hover:text-purple-600 transition-colors'
    )


# %% ../nbs/my-blog.ipynb #0695f49d
def research():
    entries = [
        {'title': 'Evidence of non-additional pig manure offset projects', 'author_str': 'Grayson Badgley + Freya Chay',
        'yr': 2026,
        'outlet': 'EarthArXiv', 'doi': 'https://eartharxiv.org/repository/view/12767/'},
        {'title': 'Towards more effective nature-based climate solutions in global forests',
        'author_str': 'Bill Anderegg et al.', 'yr': 2025, 'outlet': 'Nature',
        'doi': 'https://doi.org/10.1038/s41586-025-09116-6'},
        {'title': 'Funding forests\' climate potential without carbon offsets',
        'author_str': 'Libby Blanchard et al.', 'yr': 2024, 'outlet': 'One Earth',
        'doi': 'https://doi.org/10.1016/j.oneear.2024.05.007'},
        {'title': 'Carbon offsets are incompatible with the Paris Agreement', 'author_str': 'Danny Cullenward et al.',
        'yr': 2023, 'outlet': 'One Earth', 'doi': 'https://doi.org/10.1016/j.oneear.2023.09.003'},
        {'title': 'Future climate risks from stress, insects and fire across US forests',
        'author_str': 'Bill Anderegg et al.', 'yr': 2022, 'outlet': 'Ecology Letters',
        'doi': 'https://doi.org/10.1111/ele.14018'},
        {
            'title': 'NIRVP: A robust structural proxy for sun-induced chlorophyll fluorescence and photosynthesis across scales',
            'author_str': 'Ben Dechant et al.', 'yr': 2022, 'outlet': 'Remote Sensing of Environment',
            'doi': 'https://doi.org/10.1016/j.rse.2021.112763'},
        {
            'title': 'Combining near-infrared radiance of vegetation and fluorescence spectroscopy to detect effects of abiotic changes and stresses',
            'author_str': 'Yelu Zeng et al.', 'yr': 2022, 'outlet': 'Remote Sensing of Environment',
            'doi': 'https://doi.org/10.1016/j.rse.2021.112856'},
        {
            'title': 'Using remote sensing to quantify the additional climate benefits of California forest carbon offset projects',
            'author_str': 'Shane Coffield et al.', 'yr': 2022, 'outlet': 'Global Change Biology',
            'doi': 'https://doi.org/10.1111/gcb.16380'},
        {'title': 'California\'s forest carbon offsets buffer pool is severely undercapitalized',
        'author_str': 'Badgley et al.', 'yr': 2022, 'outlet': 'Frontiers in Forests and Global Change',
        'doi': 'https://doi.org/10.3389/ffgc.2022.930426'},
        {'title': 'Systematic over‐crediting in California\'s forest carbon offsets program',
        'author_str': 'Badgley et al.', 'yr': 2022, 'outlet': 'Global Change Biology',
        'doi': 'https://doi.org/10.1111/gcb.15943'},

        {'title': 'Estimating near-infrared reflectance of vegetation from hyperspectral data',
        'author_str': 'Yelu Zeng et al.', 'yr': 2021, 'outlet': 'Remote Sensing of Environment',
        'doi': 'https://doi.org/10.1016/j.rse.2021.112563'},
        {'title': 'A radiative transfer model for solar induced fluorescence using spectral invariants theory',
        'author_str': 'Yelu Zeng et al.', 'yr': 2020, 'outlet': 'Remote Sensing of Environment',
        'doi': 'https://doi.org/10.1016/j.rse.2020.111678'},
        {'title': 'Climate-driven risks to the climate mitigation potential of forests',
        'author_str': 'Bill Anderegg et al.', 'yr': 2020, 'outlet': 'Science',
        'doi': 'https://doi.org/10.1126/science.aaz7005'},
        {'title': 'Divergent forest sensitivity to repeated extreme droughts',
        'author_str': 'Bill Anderegg et al.', 'yr': 2020, 'outlet': 'Nature Climate Change',
        'doi': 'https://doi.org/10.1038/s41558-020-00919-1'},
        {
            'title': 'Outgoing near‐infrared radiation from vegetation scales with canopy photosynthesis across a spectrum of function, structure, physiological capacity, and weather',
            'author_str': 'Dennis Baldocchi et al.', 'yr': 2020, 'outlet': 'Journal of Geophysical Research',
            'doi': 'https://doi.org/10.1029/2019JG005534'},
        {
            'title': 'Canopy structure explains the relationship between photosynthesis and sun-induced chlorophyll fluorescence in crops',
            'author_str': 'Ben Dechant et al.', 'yr': 2020, 'outlet': 'Remote Sensing of Environment',
            'doi': 'https://doi.org/10.1016/j.rse.2020.111733'},

        {'title': 'Terrestrial gross primary production: Using NIRV to scale from site to globe',
            'author_str': 'Grayson Badgley et al.', 'yr': 2019, 'outlet': 'Global Change Biology',
            'doi': 'https://doi.org/10.1111/gcb.14729'},
        {
            'title': 'A practical approach for estimating the escape ratio of near-infrared solar-induced chlorophyll fluorescence',
            'author_str': 'Yelu Zeng et al.', 'yr': 2019, 'outlet': 'Remote Sensing of Environment',
            'doi': 'https://doi.org/10.1016/j.rse.2019.04.013'
        },
        {'title': 'Within‐species patterns challenge our understanding of the leaf economics spectrum',
            'author_str': 'Leander Anderegg et al.', 'yr': 2018, 'outlet': 'Ecology Letters',
            'doi': 'https://doi.org/10.1111/ele.12945'},
        {'title': 'Mobile MUTE specifies subsidiary cells to build physiologically improved grass stomata',
            'author_str': 'Michael Raissig et al.', 'yr': 2017, 'outlet': 'Science',
            'doi': 'https://doi.org/10.1126/science.aal3254'},
        {'title': 'Canopy near-infrared reflectance and terrestrial photosynthesis',
            'author_str': 'Grayson Badgley et al.',
            'yr': 2017, 'outlet': 'Science Advances', 'doi': 'https://doi.org/10.1126/sciadv.1602244'},

        {'title': 'Improving the monitoring of crop productivity using spaceborne solar‐induced fluorescence',
            'author_str': 'Kaiyu Guan et al.', 'yr': 2016, 'outlet': 'Global Change Biology',
            'doi': 'https://doi.org/10.1111/gcb.13136'},
        {
            'title': 'On uncertainty in global terrestrial evapotranspiration estimates from choice of input forcing datasets',
            'author_str': 'Grayson Badgley et al.', 'yr': 2015, 'outlet': 'Journal of Hydrometeorology',
            'doi': 'https://doi.org/10.1175/JHM-D-14-0040.1'
        },
        {'title': 'Forest productivity and water stress in Amazonia: Observations from GOSAT chlorophyll fluorescence',
            'author_str': 'Jung-Eun Lee et al.', 'yr': 2013, 'outlet': 'Proceedings of the Royal Society B',
            'doi': 'https://doi.org/10.1098/rspb.2013.0171'},
        {'title': 'Global nutrient limitation in terrestrial vegetation', 'author_str': 'Josh Fisher et al.',
            'yr': 2012, 'outlet': 'Global Biogeochemical Cycles', 'doi': 'https://doi.org/10.1029/2011GB004252'},
        {
            'title': 'New global observations of the terrestrial carbon cycle from GOSAT: Patterns of plant fluorescence with gross primary productivity',
            'author_str': 'Christian Frankenberg et al.', 'yr': 2011, 'outlet': 'Geophysical Research Letters',
            'doi': 'https://doi.org/10.1029/2011GL048738'}
    ]

    return Div(*[research_entry(**entry) for entry in entries], cls='space-y-4')

# %% ../nbs/my-blog.ipynb #31dc21a3
@rt('/writing')
def get(): return Title("Writing"), Div(navbar(), writing(), footer(), cls='min-h-screen flex flex-col')

# %% ../nbs/my-blog.ipynb #97380a1a
def get_note_paths():
    return list(Path('notes').glob('*.md'))


def previews():
    note_paths = get_note_paths()
    preview_d = {}
    for note_path in note_paths:
        note = load_note(note_path)
        preview_d[note.get('date')] = preview_entry(note) # can only have one post a day — that's fine!

    preview_d = dict(sorted(preview_d.items(), reverse=True))

    return Container(H2("Notes"), *preview_d.values(), cls=(ContainerT.xs, 'space-y-4 pt-16 w-full'))


def load_note(fn):
    with open(fn) as f:
        note = frontmatter.load(f)
        note['slug'] = Path(fn).stem
        return note


def preview_entry(note):
    return A(
        Div(
            P(Strong(note.get('title'))), 
            P(note.get('preview'), cls='!text-black'),        
        ),
        href=f'notes/{note.get("slug")}', cls='block space-y-2 text-black hover:text-purple-600 transition-colors'
    )

    

# %% ../nbs/my-blog.ipynb #1c1b5cab
def full_note(slug):
    note = load_note(f'notes/{slug}.md')
    return Container(H2(note.get('title'), cls='pb-4'), Div(note.content, cls='!text-left'), cls=(ContainerT.xs, 'pt-16 w-full'))

@rt('/notes/{slug}')
def get(slug: str):
    return Title("Note"), Div(navbar(), full_note(slug), footer(), cls='min-h-screen flex flex-col')
    

@rt('/notes')
def get(): return Title("Notes"), Div(navbar(), previews(), footer(), cls='min-h-screen flex flex-col')

# %% ../nbs/my-blog.ipynb #a564b7f7
if __name__ == '__main__':
    serve(port=5002)
